/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author elliotfrias
 */
public class Game1 extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
     String personaSeleccionada = "";
     
    
    public Game1() { 
        initComponents();
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        persona1 = new javax.swing.JLabel();
        persona2 = new javax.swing.JLabel();
        persona3 = new javax.swing.JLabel();
        persona4 = new javax.swing.JLabel();
        persona5 = new javax.swing.JLabel();
        persona6 = new javax.swing.JLabel();
        persona7 = new javax.swing.JLabel();
        persona8 = new javax.swing.JLabel();
        persona9 = new javax.swing.JLabel();
        persona10 = new javax.swing.JLabel();
        persona11 = new javax.swing.JLabel();
        persona12 = new javax.swing.JLabel();
        persona13 = new javax.swing.JLabel();
        persona14 = new javax.swing.JLabel();
        persona15 = new javax.swing.JLabel();
        persona16 = new javax.swing.JLabel();
        persona17 = new javax.swing.JLabel();
        persona18 = new javax.swing.JLabel();
        persona19 = new javax.swing.JLabel();
        persona20 = new javax.swing.JLabel();
        persona21 = new javax.swing.JLabel();
        persona22 = new javax.swing.JLabel();
        persona23 = new javax.swing.JLabel();
        persona24 = new javax.swing.JLabel();
        persona25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("¡ADIVINA QUIÉN!");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        persona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona1.jpg"))); // NOI18N
        persona1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona1MouseClicked(evt);
            }
        });

        persona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona2.jpg"))); // NOI18N
        persona2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona2MouseClicked(evt);
            }
        });
        persona2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                persona2KeyPressed(evt);
            }
        });

        persona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona3.jpg"))); // NOI18N
        persona3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona3MouseClicked(evt);
            }
        });

        persona4.setBackground(new java.awt.Color(255, 51, 51));
        persona4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona4.jpg"))); // NOI18N
        persona4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona4MouseClicked(evt);
            }
        });

        persona5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona5.jpg"))); // NOI18N
        persona5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona5MouseClicked(evt);
            }
        });

        persona6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona6.jpg"))); // NOI18N
        persona6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona6MouseClicked(evt);
            }
        });

        persona7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona7.jpg"))); // NOI18N
        persona7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona7MouseClicked(evt);
            }
        });

        persona8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona8.jpg"))); // NOI18N
        persona8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona8MouseClicked(evt);
            }
        });

        persona9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona9.jpg"))); // NOI18N
        persona9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona9MouseClicked(evt);
            }
        });

        persona10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona10.jpg"))); // NOI18N
        persona10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona10MouseClicked(evt);
            }
        });

        persona11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona11.jpg"))); // NOI18N
        persona11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona11MouseClicked(evt);
            }
        });

        persona12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona12.jpg"))); // NOI18N
        persona12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona12MouseClicked(evt);
            }
        });

        persona13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona13.jpg"))); // NOI18N
        persona13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona13MouseClicked(evt);
            }
        });

        persona14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona14.jpg"))); // NOI18N
        persona14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona14MouseClicked(evt);
            }
        });

        persona15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona15.jpg"))); // NOI18N
        persona15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona15MouseClicked(evt);
            }
        });

        persona16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona16.jpg"))); // NOI18N
        persona16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona16MouseClicked(evt);
            }
        });

        persona17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona17.jpg"))); // NOI18N
        persona17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona17MouseClicked(evt);
            }
        });

        persona18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona18.jpg"))); // NOI18N
        persona18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona18MouseClicked(evt);
            }
        });

        persona19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona19.jpg"))); // NOI18N
        persona19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona19MouseClicked(evt);
            }
        });

        persona20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona20.jpg"))); // NOI18N
        persona20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona20MouseClicked(evt);
            }
        });

        persona21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona21.jpg"))); // NOI18N
        persona21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona21MouseClicked(evt);
            }
        });

        persona22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona22.jpg"))); // NOI18N
        persona22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona22MouseClicked(evt);
            }
        });

        persona23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona23.jpg"))); // NOI18N
        persona23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona23MouseClicked(evt);
            }
        });

        persona24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona24.jpg"))); // NOI18N
        persona24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona24MouseClicked(evt);
            }
        });

        persona25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/persona25.jpg"))); // NOI18N
        persona25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                persona25MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona1)
                    .addComponent(persona6)
                    .addComponent(persona11)
                    .addComponent(persona16)
                    .addComponent(persona21))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persona7)
                            .addComponent(persona2)
                            .addComponent(persona12)
                            .addComponent(persona17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(persona22)
                        .addGap(78, 78, 78)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona3)
                    .addComponent(persona8)
                    .addComponent(persona13)
                    .addComponent(persona18)
                    .addComponent(persona23))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona4)
                    .addComponent(persona9)
                    .addComponent(persona14)
                    .addComponent(persona19)
                    .addComponent(persona24))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(persona5))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(persona10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(persona15)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(persona20)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(persona25)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(persona1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(persona5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(persona4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(persona3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(persona2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona8)
                    .addComponent(persona9)
                    .addComponent(persona10)
                    .addComponent(persona7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona6))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona12)
                    .addComponent(persona11)
                    .addComponent(persona13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona14)
                    .addComponent(persona15))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona16)
                    .addComponent(persona18, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona19, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona20))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(persona22, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona21)
                    .addComponent(persona23, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persona24)
                    .addComponent(persona25))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void persona2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_persona2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_persona2KeyPressed

    private void persona2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona2MouseClicked
        System.out.println("Persionaste la persona 2");
        personaSeleccionada = "Persona Zuhra";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona2.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_persona2MouseClicked

    private void persona3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona3MouseClicked
        System.out.println("Persionaste la persona 3");
        personaSeleccionada = "Persona Robert";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona3.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_persona3MouseClicked

    private void persona4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona4MouseClicked
        System.out.println("Persionaste la persona 4");
        personaSeleccionada = "Persona Caroline";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona4.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona4MouseClicked

    private void persona5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona5MouseClicked
        System.out.println("Persionaste la persona 5");
        personaSeleccionada = "Persona Rolando";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona5.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }
       
        

    }//GEN-LAST:event_persona5MouseClicked

    private void persona6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona6MouseClicked
        System.out.println("Persionaste la persona 6");
         personaSeleccionada = "Persona Anastasia";
         Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona6.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_persona6MouseClicked

    private void persona7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona7MouseClicked
        System.out.println("Persionaste la persona 7");
        personaSeleccionada = "Persona Ankit";    
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona7.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona7MouseClicked

    private void persona8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona8MouseClicked
        System.out.println("Persionaste la persona 8");
                personaSeleccionada = "Persona Vinita";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona8.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_persona8MouseClicked

    private void persona9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona9MouseClicked
        System.out.println("Persionaste la persona 9");
                personaSeleccionada = "Persona Joshua";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona9.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona9MouseClicked

    private void persona10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona10MouseClicked
        System.out.println("Persionaste la persona 10");
                personaSeleccionada = "Persona Alimatou";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona10.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona10MouseClicked

    private void persona11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona11MouseClicked
        System.out.println("Persionaste la persona 11");
                personaSeleccionada = "Persona Carlos";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona11.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona11MouseClicked

    private void persona12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona12MouseClicked
        System.out.println("Persionaste la persona 12");
                personaSeleccionada = "Persona Carmen";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona12.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona12MouseClicked

    private void persona13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona13MouseClicked
        System.out.println("Persionaste la persona 13");
                personaSeleccionada = "Persona Peter";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona13.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona13MouseClicked

    private void persona14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona14MouseClicked
        System.out.println("Persionaste la persona 14");
                personaSeleccionada = "Persona Elsa";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona14.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona14MouseClicked

    private void persona15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona15MouseClicked
        System.out.println("Persionaste la persona 15");
                personaSeleccionada = "Persona John";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona15.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona15MouseClicked

    private void persona16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona16MouseClicked
        System.out.println("Persionaste la persona 16");
        personaSeleccionada = "Persona Hermela";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona16.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona16MouseClicked

    private void persona17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona17MouseClicked
        System.out.println("Persionaste la persona 17");
                personaSeleccionada = "Persona Arnoud";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona17.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona17MouseClicked

    private void persona18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona18MouseClicked
        System.out.println("Persionaste la persona 18");
                personaSeleccionada = "Persona Li";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona18.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona18MouseClicked

    private void persona19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona19MouseClicked
        System.out.println("Persionaste la persona 19");
                personaSeleccionada = "Persona Yonas";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona19.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona19MouseClicked

    private void persona20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona20MouseClicked
        System.out.println("Persionaste la persona 20");
                personaSeleccionada = "Persona Rosa";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona20.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona20MouseClicked

    private void persona21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona21MouseClicked
        System.out.println("Persionaste la persona 21");
                personaSeleccionada = "Persona Ed";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona21.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona21MouseClicked

    private void persona22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona22MouseClicked
        System.out.println("Persionaste la persona 22");
                personaSeleccionada = "Persona Nathaline";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona22.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona22MouseClicked

    private void persona23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona23MouseClicked
        System.out.println("Persionaste la persona 23");   
        personaSeleccionada = "Persona Hector";
        Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona23.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona23MouseClicked

    private void persona24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona24MouseClicked
        System.out.println("Persionaste la persona 24");
                personaSeleccionada = "Persona Elizabeth";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona24.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona24MouseClicked

    private void persona25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona25MouseClicked
        System.out.println("Persionaste la persona 25");
                personaSeleccionada = "Persona Mustafa";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona25.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_persona25MouseClicked

    private void persona1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_persona1MouseClicked
        System.out.println("Persionaste la persona 1");
                personaSeleccionada = "Persona Moussa";
                Image nuevoIcono;
        try {
            nuevoIcono = ImageIO.read(getClass().getResource("../IMG/ventana.png"));
            persona1.setIcon(new ImageIcon(nuevoIcono));
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_persona1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        System.out.println("");
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel persona1;
    private javax.swing.JLabel persona10;
    private javax.swing.JLabel persona11;
    private javax.swing.JLabel persona12;
    private javax.swing.JLabel persona13;
    private javax.swing.JLabel persona14;
    private javax.swing.JLabel persona15;
    private javax.swing.JLabel persona16;
    private javax.swing.JLabel persona17;
    private javax.swing.JLabel persona18;
    private javax.swing.JLabel persona19;
    private javax.swing.JLabel persona2;
    private javax.swing.JLabel persona20;
    private javax.swing.JLabel persona21;
    private javax.swing.JLabel persona22;
    private javax.swing.JLabel persona23;
    private javax.swing.JLabel persona24;
    private javax.swing.JLabel persona25;
    private javax.swing.JLabel persona3;
    private javax.swing.JLabel persona4;
    private javax.swing.JLabel persona5;
    private javax.swing.JLabel persona6;
    private javax.swing.JLabel persona7;
    private javax.swing.JLabel persona8;
    private javax.swing.JLabel persona9;
    // End of variables declaration//GEN-END:variables

    String personaSeleccionada() {
        return personaSeleccionada;
    }

    
}
